repos:
- repo: local
  hooks:
  - id: ruff-format
    name: ruff formatter
    description: This checks python formatting with ruff
    language: python
    types: [python]
    entry: ruff format
    args: ["--check"]
  
  - id: ruff-lint
    name: ruff linter
    description: This checks python files with ruff
    language: python
    types: [python]
    entry: ruff check
    args: ["--extend-select", "I"]
  
  - id: pyrefly
    name: pyrefly type checker
    description: This checks python files with pyrefly
    language: python
    types: [python]
    entry: pyrefly check
    args: []
